

DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS PRODUCES;
DROP TABLE IF EXISTS WORKS_ON;
DROP TABLE IF EXISTS SUBDEPARTMENT;
DROP TABLE IF EXISTS COLOUR;
DROP TABLE IF EXISTS SHIPPING;
DROP TABLE IF EXISTS LOADING;
DROP TABLE IF EXISTS GIFT;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS Raw_Material;
DROP TABLE IF EXISTS GIFTTYPE;
DROP TABLE IF EXISTS LOCALIZATION;
DROP TABLE IF EXISTS ELF;

CREATE TABLE CUSTOMER (
    Customer_ID INT NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50),
    Street VARCHAR(50) NOT NULL,
    House_num INT NOT NULL,
    Postal_Code VARCHAR(50) NOT NULL,
    CONSTRAINT PKCUSTID PRIMARY KEY (Customer_ID)
);
CREATE TABLE ELF (
    Elf_ID INT NOT NULL,
    YearofExperience INT NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    CONSTRAINT PKELFID PRIMARY KEY (Elf_ID)
);
CREATE TABLE LOCALIZATION (
    Localization_ID INT NOT NULL,
    Name VARCHAR(50),
    CONSTRAINT PKLOCID PRIMARY KEY (Localization_ID)
);
CREATE TABLE GIFTTYPE (
    Type_ID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    CONSTRAINT PKGIFTTYPE PRIMARY KEY (Type_ID)
);
CREATE TABLE Raw_Material (
    Raw_Material_ID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Quantity INT,
    Complexity DECIMAL,
    CONSTRAINT PKRAWMID PRIMARY KEY (Raw_Material_ID)
);
CREATE TABLE DEPARTMENT (
    Department_ID INT NOT NULL,
    Manager_ID INT NOT NULL,
    Raw_Material_ID INT,
    Name VARCHAR(50) NOT NULL,
    Raw_M_QTY INT DEFAULT 1,
    CONSTRAINT PKDEPID PRIMARY KEY (Department_ID),
    CONSTRAINT MDID UNIQUE (Manager_ID),
    CONSTRAINT FKRAWMID FOREIGN KEY (Raw_Material_ID)
        REFERENCES Raw_Material (Raw_Material_ID),
    CONSTRAINT FKELFID FOREIGN KEY (Manager_ID)
        REFERENCES ELF (ELF_ID)
);
CREATE TABLE GIFT (
    Gift_ID INT NOT NULL,
    Serial_Code VARCHAR(50) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Localized_Version VARCHAR(50) NOT NULL,
    Size VARCHAR(50) NOT NULL,
    GiftType INT NOT NULL,
    State VARCHAR(50) NOT NULL,
    Localization INT,
    TrackingNun VARCHAR(50) NOT NULL,
	ProductionDeadline  DATE,
    CONSTRAINT PKGIFTID PRIMARY KEY (Gift_ID),
    CONSTRAINT USERIAL UNIQUE (Serial_Code),
    CONSTRAINT FKGIFTTYPEID FOREIGN KEY (GiftType)
        REFERENCES GIFTTYPE (Type_ID),
    CONSTRAINT FKLOCID FOREIGN KEY (Localization)
        REFERENCES LOCALIZATION (Localization_ID)
);
CREATE TABLE LOADING (
    Load_ID INT NOT NULL,
    LoadName VARCHAR(50),
    Date DATE,
    Gift INT NOT NULL,
    SubDepartment INT NOT NULL,
    CONSTRAINT PKLOADID PRIMARY KEY (Load_ID),
    CONSTRAINT FKGIFTID FOREIGN KEY (Gift)
        REFERENCES GIFT (Gift_ID)
);
CREATE TABLE SHIPPING (
    Shipping_ID INT NOT NULL,
    ShippingDate DATE,
    Loading INT,
    CONSTRAINT PKSHIPID PRIMARY KEY (Shipping_ID),
    CONSTRAINT FKLOADID FOREIGN KEY (Loading)
        REFERENCES LOADING (Load_ID)
);
CREATE TABLE COLOUR (
    Colour_ID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Gift_ID INT NOT NULL,
    PRIMARY KEY (Colour_ID , Gift_ID)
);
CREATE TABLE Letters (
    Letter_ID INT NOT NULL,
    Customer_ID INT NOT NULL,
    Department INT NOT NULL,
    PRIMARY KEY (Letter_ID ),
    FOREIGN KEY (Department)
        REFERENCES DEPARTMENT (Department_ID)
);

CREATE TABLE SUBDEPARTMENT (
    SubDepartment_ID INT NOT NULL,
    Department INT NOT NULL,
    Name VARCHAR(50),
    CONSTRAINT PKSUBDID PRIMARY KEY (SubDepartment_ID),
    CONSTRAINT FKSUBD_DEPID FOREIGN KEY (Department)
        REFERENCES DEPARTMENT (Department_ID)
);
CREATE TABLE WORKS_ON (
    GiftType INT NOT NULL,
    Department INT NOT NULL,
    Elf INT NOT NULL,
    PRIMARY KEY (GiftType , Department),
    FOREIGN KEY (Department)
        REFERENCES DEPARTMENT (Department_ID),
    FOREIGN KEY (GiftType)
        REFERENCES GIFTTYPE (Type_ID),
    FOREIGN KEY (Elf)
        REFERENCES ELF (Elf_ID)
);
CREATE TABLE PRODUCES (
    Hours DECIMAL,
    GiftType INT NOT NULL,
    Elf INT NOT NULL,
    Quantity INT,
    Department INT,
    PRIMARY KEY (GiftType),
    FOREIGN KEY (GiftType)
        REFERENCES GIFTTYPE (Type_ID),
    FOREIGN KEY (Elf)
        REFERENCES ELF (Elf_ID),
    FOREIGN KEY (Department)
        REFERENCES DEPARTMENT (Department_ID)
);
CREATE TABLE REQUEST (
    Gift INT NOT NULL,
    Customer INT NOT NULL,
    PRIMARY KEY (Gift),
    FOREIGN KEY (Gift)
        REFERENCES GIFT (Gift_ID),
    FOREIGN KEY (Customer)
        REFERENCES CUSTOMER (Customer_ID)
);
    
    
    
    
 