
SELECT  Department.Name ,PRODUCES.GiftType,PRODUCES.Elf,PRODUCES.Quantity
FROM PRODUCES
INNER JOIN Department ON PRODUCES.Department = department.Department_ID
 WHERE PRODUCES.QUANTITY < 30;
 
 
SELECT  Elf.FirstName, Elf.LastName ,PRODUCES.GiftType,PRODUCES.Department,PRODUCES.Quantity
FROM PRODUCES
INNER JOIN Elf ON PRODUCES.Elf = ELF.ELF_ID
 WHERE PRODUCES.QUANTITY < 30;